import {ReactNode} from 'react'
import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: "My Portfolio",
  description: "Generated by George",
}


const RootLayout = ({ children }: {children: ReactNode}) => {
  return (
    <html lang='eng'>
      <body>
        <header>
          <div className='menu order-md-2 ms-sm-3 me-md-3'>
            <input type="checkbox" id='toggle' className='checkbox-toggle' />
            <label htmlFor="toggle" className='hamburger'>
              <span></span>
              <span></span>
              <span></span>
            </label>
            <nav className="main-menu">
              <ul>
                <li><Link className='nav-item' href='/'>Home</Link></li>
                <li><Link className='nav-item' href='#About'>About</Link></li>
                <li><Link className='nav-item' href='#Skills'>Skills</Link></li>
                <li><Link className='nav-item' href='#Project'>Project</Link></li>
                <li><Link className='nav-item' href='/Contact'>Contact</Link></li>
              </ul>
              <Link href='/' className='text-decoration-none logo-link ms-3 d-lg-none'><h1 className='logo'>GEORIGE</h1></Link>
            </nav>
          </div>
          <div className='order-md-1 me-sm-3 ms-md-3'>
            <Link href='/' className='text-decoration-none logo-link'><h1 className='logo'>GEORIGE</h1></Link>
          </div>
          
        </header>
        

        {children}
      </body>
      
    </html>
  )
}

export default RootLayout
